# Application name
spring.application.name=user-management-auth

# Disable Docker Compose auto-start
spring.docker.compose.enabled=false

# Application HTTP port
server.port=8080

# ==============================
# MYSQL
# ==============================

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/user_db
spring.datasource.username=root
spring.datasource.password=password

# ==============================
# JPA / Hibernate
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect