spring.application.name=order-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

jwt.secret=your-very-long-secret-key-for-learning-project-123456789
logging.level.org.springframework.security=TRACE